### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by zdolny** [zosiasz/JavaScript#1]
- [x] zobacz, co masz w repozytorium: https://scr.hu/nLB8Rd Podejrzewam, ze wlecialy tu rzeczy z innego repo. Zaznaczone elementy na screenie sa do usuniecia. Po usunieciu katalogow musisz zrobic cos, co moze wydawac sie nieintuicyjne, czyli dodac do stage'a usuniete elementy `git add -A`, zakomitowac zmiany i wypushowac. Chodzi o to, ze wszystkie zmiany w plikach/katalogach w folderze bedacym repozytorium gita, sa przez niego sledzone i musza byc komitowane
- [x] js nie dziala, bo w htmlu dodajesz go ze zlej lokalizacji

**Comment by zdolny** [comment]
jest git, o to chodzilo
jeszcze zamiast podawac swoje imie wpisz zdanie pytajace o imie - to, co podasz w okienku prompt wpadnie do zmiennej `name`

**Comment by zosiasz** [comment]
no właśnie, właśnie, zapomniałam o to zapytać, poprawione!!!

**Comment by zdolny** [comment]
elegancko
